---
apiVersion: v1
kind: Service
metadata:
  name: wil-playground-service
spec:
  ports:
    - name: "http"
      port: 80
      targetPort: 8888
      nodePort: 8888
  type: NodePort
  selector:
    app: wil-playground
