apiVersion: v1
kind: Service
metadata:
  name: wil-playground-service-test
  namespace: dev
spec:
  type: NodePort
  selector:
    app: wil-playground
  ports:
    - name: "http"
      port: 80
      targetPort: 8888
      nodePort: 30080
